# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

2.1.3


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vec = np.zeros(10)     # For all element zeros
null_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
null_vec.itemsize * null_vec.size  # 8bytes for each element and total 10 elements in array

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)            # help function opens the doc inside

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vec_1 = np.zeros(10)
null_vec_1[4] = 1
null_vec_1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.random.seed(20)
random_val = np.random.randint(10,29,size=(10))
random_val

array([13, 25, 19, 21, 17, 12, 10, 18, 26, 16], dtype=int32)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
random_val = random_val[::-1]
random_val

array([16, 26, 18, 10, 12, 17, 21, 19, 25, 13], dtype=int32)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
three_x_three = np.array([[0,1,2],
                        [3,4,5],
                        [6,7,8]])

three_x_three

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr = np.array([1,2,0,0,4,0])
print(np.where(arr == 0))

(array([2, 3, 5]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.seed(30)
random_val_1 = np.random.randint(1,100,size=(3,3,3))
random_val_1

array([[[38, 38, 46],
        [46, 13, 24],
        [ 3, 54, 18]],

       [[47,  4, 42],
        [ 8, 66, 50],
        [46, 62, 36]],

       [[19, 19, 77],
        [17,  7, 63],
        [28, 47, 46]]], dtype=int32)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
np.random.seed(10)
random_val_2 = np.random.randint(1,100,size = (10,10))
print(random_val_2)
print("max:- ", random_val_2.max(), "min:-", random_val_2.min())

[[10 16 65 29 90 94 30  9 74  1]
 [41 37 17 12 55 89 63 34 73 79]
 [50 52 55 78 70 14 26 14 93 87]
 [31 31 90 13 66 32 58 37 28 19]
 [94 78 23 24 95 12 29 75 89 10]
 [16 19 81 72 89 12 18 47  8 76]
 [29 34 85 97 89 45  6  5 72 89]
 [89 51 55 35 16 78 89 16  7 86]
 [23 12 13 93 97 63 58 80 43 58]
 [98 51 46 41 90 74 38  1 19 24]]
max:-  98 min:- 1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.random.seed(40)
vec_30 = np.random.randint(1,100,size = (30))
print(vec_30, "\n mean:-", vec_30.mean())

[71 92  8 38 57 51 66 13 72 20 32 75 56 84 60 92 74 97 50 54 74  9 53 31
 80 15 93 59 75 23] 
 mean:- 55.8


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
zero_and_one = np.full((5,5),1)
zero_and_one[1:4,1:4] = 0
zero_and_one


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
arr_1 = np.ones((2,2))
arr_1 = np.pad(arr,pad_width=1,mode='constant', constant_values=0)          #pad function adds extra value around the existing value 
# arr is name of array, pad_width specifies the number of rows/cols to be badded from each direction, mode = constant is for the borders
# constant_values = 0 is the value used for padding 

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0* np.nan) # anything *,/,+,-,% nan = na
print(np.nan == np.nan)     #nan != nan == true else false
print(np.inf > np.nan)      #inf is infinity and inf != nan == true else everything els eis false;
print(np.nan - np.nan)
print(np.nan in set([np.nan]))   #set stores object identity so this is true
print(0.3 == 3 * 0.1)               # coz in float 3*0.1 == 0.30000000000004 or any other number but not exactly = 3

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
arr = np.diag(1 + np.arange(4), k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
checkerboard = (np.indices((8,8)).sum(axis=0) % 2)
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
shape = (6, 7, 8)
index = np.unravel_index(99, shape)    # this function can find the index of any element provides, its shape is given 
print(index)


(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a= np.array([[0,1],
            [1,0]])
checkerboard_1 = np.tile(a,(4,4))       #tile function is used to repeat any string any number of times, tile(1D-array, times)(for 1D) and 
                                        #tile(2D-array,(no.of times in row, no.of times in col))
checkerboard_1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
np.random.seed(50)
arr_2 = np.random.randint(1,10,(5,5))
# There are total three Types of Normalization
#1. Min-Max Normalization  
norm_1 = (arr_2-arr_2.min())/(arr_2.max()-arr_2.min())    #range [0,1] or [-1,1], best for neural networks, images
print("Min-Max Normalization:- \n",  norm_1, "\n")

#2. Z-score
norm_2 = (arr_2-arr_2.mean())/arr_2.std()                 #Scales data to mean=0 and std=1, good for static, linear model
print("Z- Score Normalization:- \n",  norm_2, "\n")

#3. vector normalization
norm_3 = arr_2/np.linalg.norm(arr_2)                    #returns a unti length vector, Distance based model
print("Vector Normalization:- \n",  norm_3, "\n")


Min-Max Normalization:- 
 [[0.         0.         0.14285714 0.57142857 0.85714286]
 [0.71428571 0.85714286 0.85714286 0.71428571 0.28571429]
 [1.         0.57142857 0.42857143 0.85714286 0.57142857]
 [0.14285714 0.71428571 0.         0.85714286 0.42857143]
 [0.28571429 0.42857143 0.42857143 0.42857143 0.28571429]] 

Z- Score Normalization:- 
 [[-1.67245852 -1.67245852 -1.19186699  0.2499076   1.21109066]
 [ 0.73049913  1.21109066  1.21109066  0.73049913 -0.71127546]
 [ 1.69168219  0.2499076  -0.23068393  1.21109066  0.2499076 ]
 [-1.19186699  0.73049913 -1.67245852  1.21109066 -0.23068393]
 [-0.71127546 -0.23068393 -0.23068393 -0.23068393 -0.71127546]] 

Vector Normalization:- 
 [[0.04048882 0.04048882 0.08097763 0.20244408 0.28342172]
 [0.2429329  0.28342172 0.28342172 0.2429329  0.12146645]
 [0.32391053 0.20244408 0.16195527 0.28342172 0.20244408]
 [0.08097763 0.2429329  0.04048882 0.28342172 0.16195527]
 [0.12146645 0.16195527 0.16195527 0.16195527 0.12146645]] 



#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
import numpy as np

rgba = np.dtype([
    ('r', np.uint8),   #uint8 is 8 bit unsigned integer i.e. only +ve int 0-255
    ('g', np.uint8), 
    ('b', np.uint8),   
    ('a', np.uint8)    
])

print(rgba)

colors = np.array([(255, 0, 0, 255), (0, 255, 0, 128)], dtype=rgba)
print(colors)
print(colors['r'])  



[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
[(255,   0, 0, 255) (  0, 255, 0, 128)]
[255   0]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
np.random.seed(60)
arr_5x3 = np.random.randint(1,100,(5,3))
arr_3x2 = np.random.randint(1,100,(3,2))
print(arr_5x3)
print(arr_3x2)
mat_mul = np.matmul(arr_5x3,arr_3x2)
mat_mul

[[78 66 71]
 [11 16 73]
 [18 35 34]
 [88 41 45]
 [99 41 55]]
[[68 61]
 [33 91]
 [68 48]]


array([[12310, 14172],
       [ 6240,  5631],
       [ 4691,  5915],
       [10397, 11259],
       [11825, 12410]], dtype=int32)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
np.random.seed(70)
arr_3 = np.random.randint(1,10,10)
arr_3[(arr_3>3) & (arr_3<8)] *= -1
arr_3

array([-7,  3,  9,  1, -5, -6, -6, -6, -5,  8], dtype=int32)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
    Z**Z
    2 << Z >> 2
    Z <- Z
    1j*Z
    Z/1/1
    Z<Z>Z
```

In [28]:
   # Z**Z
   # 2 << Z >> 2
    #    1j*Z
    #Z/1/1



#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
 # all three get a runtime warning
np.array(0) / np.array(0)       #not defined or NAN
np.array(0) // np.array(0)      #not defined or NAN
np.array([np.nan]).astype(int).astype(float)        #random float values

C:\Users\Aniket\AppData\Local\Temp\ipykernel_3332\1667707339.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)       #not defined or NAN
C:\Users\Aniket\AppData\Local\Temp\ipykernel_3332\1667707339.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)      #not defined or NAN
C:\Users\Aniket\AppData\Local\Temp\ipykernel_3332\1667707339.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)        #random float values


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
arr_4 = np.array([1.2, 9.0,-10.88, 9.6, -4.3]) 
np.where(arr_4>0, np.ceil(arr_4), np.floor(arr_4))

array([  2.,   9., -11.,  10.,  -5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
np.random.seed(80)
arr_5 = np.random.randint(1,10,5)
arr_6 = np.random.randint(1,10,5)
print(arr_5)
print(arr_6)
common = np.intersect1d(arr_5, arr_6)
print(common)

[7 4 3 4 7]
[8 8 4 2 6]
[4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
np.seterr(all = 'ignore')       # Function to ignore Warning
np.array(0) // np.array(0)

np.int64(0)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)        # false

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')
print("Today:- ", today)
print("Yesterday:- ", yesterday)
print("Tomorrow:- ", tomorrow)

Today:-  2025-11-25
Yesterday:-  2025-11-24
Tomorrow:-  2025-11-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
july_2016

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
np.random.seed(90)
A = np.ones((2,3))
B = np.random.random((2,3))
A += B
A *= -0.5
A

array([[-0.5765271 , -0.57884283, -0.99274556],
       [-0.95224887, -0.59303913, -0.63385476]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
np.random.seed(100)
arr_pos = np.random.uniform(1,10,10)        # the uniform function generates random float values in given range
print(arr_pos.astype(int))
print(np.floor(arr_pos))
print(np.trunc(arr_pos))
print(arr_pos - (arr_pos % 1))


[5 3 4 8 1 2 7 8 2 6]
[5. 3. 4. 8. 1. 2. 7. 8. 2. 6.]
[5. 3. 4. 8. 1. 2. 7. 8. 2. 6.]
[5. 3. 4. 8. 1. 2. 7. 8. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
np.arange(5).reshape(5,1) + np.zeros((1,5))         # this creates a 5x5 matrix as pandas expand the matrix by broadcasting
# broadcasting is the method of expanding the smaller array to match the shape of larger array without actually copying the data

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(), dtype=int, count=-1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
np.linspace(0,1,12, endpoint=False)[1:-1]     # linspace function creates evenly spaced values between given range, here 12 values are created and first and last are excluded
#or:- np.random.seed(110)
# np.random.rand(10)      # this works because rand function generates values between 0 and 1 by default excluding them

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
np.random.seed(120)
arr_7 = np.random.rand(3,3)
arr_7

array([[0.67795555, 0.5129588 , 0.62370571],
       [0.47714247, 0.46025981, 0.95086487],
       [0.9845756 , 0.85442255, 0.59109035]])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
# cupy.sum() from cuda12x can be used to sum small array faster than np.sum() as it uses GPU for computation

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [43]:
np.random.seed(130)
A = np.random.randint(1,10,(3,3))
B = np.random.randint(1,10,(3,3))

print(A)    #arr A
print(B)    #arr B

print(A == B)   # element-wise comparison of two arrays

print(np.array_equal(A,B))   # checks if two arrays are equal or not

[[6 4 2]
 [1 7 9]
 [8 1 6]]
[[8 2 7]
 [2 8 3]
 [2 5 9]]
[[False False False]
 [False False False]
 [False False False]]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
arr_8= np.zeros(10)
arr_8.flags.writeable = False   #the flags.writeable set to False makes the array immutable
arr[0] =1   #this will raise an error

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
np.random.seed(140)
cartesian_coords = np.random.rand(10,2)
x = cartesian_coords[:,0]
y = cartesian_coords[:,1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)
polar_coords = np.column_stack((r, theta))      #the column_stack function is used to stack 1D arrays as columns into a 2D array
polar_coords


array([[0.75576807, 0.14437095],
       [0.29656494, 1.56747571],
       [0.32064369, 1.56465707],
       [0.59846633, 1.41564997],
       [0.93171093, 1.36329526],
       [1.01376866, 0.50177592],
       [0.29380865, 0.35704945],
       [0.86068218, 1.46361026],
       [0.83651704, 0.4457373 ],
       [0.88299435, 1.52580905]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
np.random.seed(150)
arr = np.random.randint(1, 10, 10)
print("Original array:", arr)

arr[arr == arr.max()] = 0
print("Modified array :", arr)


Original array: [5 1 3 5 6 8 9 4 9 2]
Modified array : [5 1 3 5 6 8 0 4 0 2]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
dt = np.dtype([('x', float), ('y', float)])
grid = np.zeros((5,5), dtype=dt)
grid['x'], grid['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))   #np.meshgrid() is a very useful NumPy function when working with grids of (x, y) coordinates
grid

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
X = np.arange(1,6)
Y = X + 0.5
C = 1.0 / (X[:, None] - Y[None, :])
C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [49]:
np.set_printoptions(threshold=np.inf)  #the set_printoptions function is used to set the printing options for numpy arrays, threshold=np.inf means that the array will be printed in its entirety without truncation
arr = np.arange(1000)
print(arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
vec = np.random.random(10)
print(vec)
target = 0.5
closest = vec[np.abs(vec - target).argmin()] # the argmin function returns the index of minimum value in the array
print(closest)


[0.64084992 0.07976302 0.23196604 0.38595151 0.23673507 0.99838317
 0.38934119 0.72383694 0.45174605 0.47687325]
0.47687324640887463


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
pos_color = np.zeros(3, dtype=[('pos', float, 2), ('color', float, 3)])
print(pos_color)

[([0., 0.], [0., 0., 0.]) ([0., 0.], [0., 0., 0.])
 ([0., 0.], [0., 0., 0.])]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
coords = np.random.random((100,2))
distances = np.sqrt(np.sum(coords**2, axis=1))  # axis=1 means sum along the rows i.e. for each coordinate pair sum of squares is calculated and then square root is taken to get the euclidean distance from origin
distances

array([0.69614948, 0.59897595, 0.91453919, 0.53011724, 0.7078281 ,
       0.58225921, 0.86732693, 0.50154065, 0.96500199, 0.85549138,
       1.15228925, 1.00682787, 0.1730308 , 0.5450758 , 1.17315445,
       0.99945974, 1.10049884, 0.34031813, 0.25187897, 1.07633526,
       0.50182588, 1.0043088 , 0.2727238 , 0.80173701, 0.84061307,
       0.12414156, 0.98951575, 0.54395977, 0.95840584, 0.81079003,
       0.92469186, 0.71725229, 0.7615933 , 0.74347203, 0.46538269,
       0.49792665, 0.58293313, 0.32135065, 1.0229053 , 0.47658928,
       1.06129776, 0.55119769, 0.4954328 , 0.43070995, 1.01873689,
       0.22182295, 0.30849644, 1.13251171, 1.04752115, 0.79429265,
       0.69402331, 0.77523313, 0.77734525, 0.47352401, 1.20579438,
       0.88909718, 0.89856862, 0.38008118, 1.00962252, 0.41665646,
       1.11678546, 0.86475795, 0.77259477, 0.82387887, 0.82070784,
       0.30264161, 0.92522431, 0.75409831, 0.8224361 , 0.29046824,
       0.6816637 , 0.72400419, 0.73999079, 1.124805  , 1.00725

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [53]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
Z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO
file = StringIO("1,2,3,4,5\n6,, ,7,8\n , ,9,10,11")
data = np.genfromtxt(file, delimiter=",")
data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
A = np.arange(9).reshape(3,3)
list(np.ndenumerate(A))     # the ndenumerate function is used to iterate over each element of the array along with its index as a tuple and is used as an equivalent of enumerate for numpy arrays
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
# the gaussian function:- e^(-(x^2 + y^2))
x = np.linspace(-1,1,10)
y = np.linspace(-1,1,10)
X,Y = np.meshgrid(x,y)
ans = np.exp(-(X**2 + Y**2))      #exp function computes e raised to the power of given value
ans

array([[0.13533528, 0.20090196, 0.27018673, 0.32919299, 0.36336564,
        0.36336564, 0.32919299, 0.27018673, 0.20090196, 0.13533528],
       [0.20090196, 0.2982341 , 0.40108566, 0.48867903, 0.53940751,
        0.53940751, 0.48867903, 0.40108566, 0.2982341 , 0.20090196],
       [0.27018673, 0.40108566, 0.53940751, 0.65720907, 0.72543221,
        0.72543221, 0.65720907, 0.53940751, 0.40108566, 0.27018673],
       [0.32919299, 0.48867903, 0.65720907, 0.8007374 , 0.88385983,
        0.88385983, 0.8007374 , 0.65720907, 0.48867903, 0.32919299],
       [0.36336564, 0.53940751, 0.72543221, 0.88385983, 0.97561098,
        0.97561098, 0.88385983, 0.72543221, 0.53940751, 0.36336564],
       [0.36336564, 0.53940751, 0.72543221, 0.88385983, 0.97561098,
        0.97561098, 0.88385983, 0.72543221, 0.53940751, 0.36336564],
       [0.32919299, 0.48867903, 0.65720907, 0.8007374 , 0.88385983,
        0.88385983, 0.8007374 , 0.65720907, 0.48867903, 0.32919299],
       [0.27018673, 0.40108566, 0.5394075

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
Z = np.zeros((10,10))
p = 10
idx = np.random.choice(100,p,replace=False)
Z[np.unravel_index(idx,(10,10))] = 1        #this unravels the 1D indices to 2D indices based on given shape and assigns 1 to those positions
Z

array([[1., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [58]:
Z = np.random.random((5,10))
Z -= Z.mean(axis=1,keepdims=True)   # keepdims=True keeps the number of dimensions same after operation
Z

array([[-0.17497973, -0.20460536,  0.24577722, -0.2276064 ,  0.13209536,
        -0.01065185, -0.13181793,  0.03771225,  0.12144413,  0.21263232],
       [-0.57545617, -0.04657032,  0.22046026,  0.31709278,  0.03850647,
         0.37112934, -0.28735349, -0.05183438, -0.2943551 ,  0.30838061],
       [-0.03622198, -0.29536801,  0.18065781,  0.19818734, -0.25334416,
         0.29759442, -0.15216885,  0.35256172,  0.15711488, -0.44901318],
       [ 0.32437704,  0.17583588, -0.22598127,  0.00069363, -0.25445993,
         0.43886222, -0.40364232,  0.28987274, -0.05974419, -0.28581381],
       [ 0.18283027,  0.12215427,  0.05022167, -0.12146306, -0.32310402,
         0.22779706, -0.34675885, -0.03629453,  0.05837571,  0.18624147]])

#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
ar= np.random.randint(0,10,(5,5))
ar[ar[:,2].argsort()]  # the argsort function returns the indices that would sort an array, here the array is sorted based on the values in 3rd column (index 2)


array([[5, 5, 3, 3, 8],
       [4, 9, 3, 0, 3],
       [4, 2, 4, 8, 3],
       [4, 3, 4, 2, 5],
       [4, 7, 8, 2, 5]], dtype=int32)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [62]:
arr_10= np.random.randint(0,2,(5,5))
~arr.any(axis=0)  # the any function checks if any of the elements along given axis is True, here axis=0 means column-wise operation and ~ negates the boolean values


np.False_

#### 61. Find the nearest value from a given value in an array (★★☆)

In [63]:
vec = np.random.random(10)
print(vec)
target = 0.5
closest = vec[np.abs(vec - target).argmin()] # the argmin function returns the index of minimum value in the array
print(closest)

[0.121989   0.779299   0.89871732 0.81186723 0.58127725 0.97844315
 0.04342091 0.31260621 0.0771398  0.09429834]
0.5812772465051702


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)